name: Validate MacOSX Clang13 case

on:
  push:
    branches: [ release/5.2.0/ci ]

    paths-ignore:
      - 'Docs/**'
      - '**.md'

jobs:
  macos-clang-13:
    runs-on: macos-13
    name: macOS Clang 13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/Build -B ${{github.workspace}}/Build/MacOS \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DTARGET_UNIT_TESTS=OFF \
              -DTARGET_HELLO_WORLD=OFF \
              -DTARGET_PERFORMANCE_TEST=OFF \
              -DTARGET_SAMPLES=OFF \
              -DTARGET_VIEWER=OFF \
              -DCROSS_PLATFORM_DETERMINISTIC=OFF \
              -DINTERPROCEDURAL_OPTIMIZATION=OFF \
              -DGENERATE_DEBUG_SYMBOLS=OFF \
              -DENABLE_ALL_WARNINGS=OFF \
              -DOVERRIDE_CXX_FLAGS=OFF \
              -DDEBUG_RENDERER_IN_DEBUG_AND_RELEASE=OFF \
              -DPROFILER_IN_DEBUG_AND_RELEASE=OFF
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/MacOS